[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

lib_deps =
  adafruit/Adafruit GFX Library
  adafruit/Adafruit SSD1306
  adafruit/DHT sensor library
  adafruit/Adafruit Unified Sensor
  adafruit/Adafruit NeoPixel        ; pour #include <Adafruit_NeoPixel.h>
  
  knolleary/PubSubClient
  bblanchon/ArduinoJson
  
  paulstoffregen/OneWire
  milesburton/DallasTemperature
  adafruit/RTClib
  
  madhephaestus/ESP32Servo          ; pour #include <ESP32Servo.h>
  marcoschwartz/LiquidCrystal_I2C   ; pour #include <LiquidCrystal_I2C.h>